### PR TITLE
feat!: add the sonarjs/recommended set of rules

### LINKED ISSUE #4: Add sonarjs/recommended set of rules
We currently use this set internally and code that is using the shared configs also configures this plugin and ruleset and mostly conforms to the rules.

### PR DESCRIPTION
**Pull request by nicktalb**
closes #4

### CODE REVIEW

**Review by ahboujelben — COMMENTED** [review]
Looks good, will "feature" be picked up by semantic-release up instead of using "feat" as mentioned in the docs?

**Comment by nicktalb** [comment]
> Looks good, will "feature" be picked up by semantic-release up instead of using "feat" as mentioned in the docs?

Thanks, possibly not. Now fixed to use "feat". If we use squash and merge then the final commit message is defined at that point. Ideally I will find a way to check the merge commit follows conventional commits...

**Review by ahboujelben — APPROVED** [review]

**Comment by nicktalb** [comment]
A new release was not created. It looks like semantic-release actually uses the `angular` preset by default.
https://github.com/semantic-release/commit-analyzer#options
We can either continue to use that or I can look at installing and configuring conventionalcommits. I'm inclined to switch the CI to conventionalcommits and then the next run of semantic-release will pick up the sonarjs change. If not,I will need to merge a commit just to pick up the `feat!` breaking change.
Thoughts?

**Comment by nicktalb** [comment]
Created #17

**Comment by ahboujelben** [comment]
Agreed, conventional commits specification looks clearer and the usage of "!" is simpler than adding BREAKING CHANGE at the footer.

**Comment by nicktalb** [comment]
Thanks. I've created a PR #17 for this change.

**Comment by nicktalb** [comment]
> > Looks good, will "feature" be picked up by semantic-release up instead of using "feat" as mentioned in the docs?
> 
> Thanks, possibly not. Now fixed to use "feat". If we use squash and merge then the final commit message is defined at that point. Ideally I will find a way to check the merge commit follows conventional commits...

On submitting a PR to semantic-release I happened across https://github.com/zeke/semantic-pull-requests which looks like it would do the job.

**Pull request merged**
